- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "07:15AM IST"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{trainer}} duration of {{duration}} timings are {{timings}}"