- name: data types
  hosts: localhost
  vars:
    course: "Devops with aws" #string
    Tools: #list
    - linux
    - shell
    - ansible
    experience: # map
      Devops: 3 # number
      aws: 2
      Dockers: 1
    Real project: true # boolean
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "course {{course}} tools covered: {{Tools}} experience is: {{experience}} real project {{Real project}}"