172.31.26.77
[web] # group 1 ,it is a group name where we can include all the hosts related to this group
172.31.26.77

[db]
172.31.26.78

[web app]
172.31.26.79

[all:children] # this is group of all groups, by mentioning the group name it will execute all the hosts in it.
web