172.31.26.77
[web] # group 1 ,it is a group name where we can include all the hosts related to this group
172.31.26.77

[web:vars]
DB_url="http://db.devopsaws78.cloud"

[localhost]
localhost 

[localhost:vars]
course= "Devops with aws"
trainer= "siva kumar"
duration= "120hrs"

[db]
172.31.26.78

[app]
172.31.26.79

[all:children] # this is group of all groups, by mentioning the group name it will execute all the hosts in it.
web
app